// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD03CRXeko4WsQknrKwUK3Pn2_zxT5tpac',
    appId: '1:717226527623:web:32a38fe1e99109634c6122',
    messagingSenderId: '717226527623',
    projectId: 'learning-dart-isaac',
    authDomain: 'learning-dart-isaac.firebaseapp.com',
    storageBucket: 'learning-dart-isaac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF6LU0qD0-4Mqdgto9VYG7_zHhUKQ6yXA',
    appId: '1:717226527623:android:62a0e02b59e5ddfa4c6122',
    messagingSenderId: '717226527623',
    projectId: 'learning-dart-isaac',
    storageBucket: 'learning-dart-isaac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL9SCNo-ts7UvXlisZPpiD95gSoMlSQdk',
    appId: '1:717226527623:ios:7f5ca6fcca7fd09c4c6122',
    messagingSenderId: '717226527623',
    projectId: 'learning-dart-isaac',
    storageBucket: 'learning-dart-isaac.appspot.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL9SCNo-ts7UvXlisZPpiD95gSoMlSQdk',
    appId: '1:717226527623:ios:2e8e88f56dc5620f4c6122',
    messagingSenderId: '717226527623',
    projectId: 'learning-dart-isaac',
    storageBucket: 'learning-dart-isaac.appspot.com',
    iosBundleId: 'com.example.learningdart.RunnerTests',
  );
}
